[project]
name = "clarity"
requirements = []
[contracts.stxlink-transfer-trait]
depends_on = []
path = "contracts/stxlink-transfer-trait.clar"

[contracts.direct-request]
path = "contracts/direct-request.clar"
depends_on = ["oracle", "stxlink-token", "stxlink-transfer-trait", "oracle-callback-trait"]

[contracts.oracle]
path = "contracts/oracle.clar"
depends_on = ["oracle-trait", "oracle-callback-trait"]

[contracts.stxlink-token]
depends_on = ["ft-trait", "restricted-token-trait", "stxlink-transfer-trait", "oracle-callback-trait"]
path = "contracts/stxlink-token.clar"

[contracts.ft-trait]
depends_on = []
path = "contracts/ft-trait.clar"

[contracts.restricted-token-trait]
depends_on = []
path = "contracts/restricted-token-trait.clar"

[contracts.oracle-trait]
depends_on = ["oracle-callback-trait"]
path = "contracts/oracle-trait.clar"

[contracts.oracle-callback-trait]
depends_on = []
path = "contracts/oracle-callback-trait.clar"