# -------------------------------------------------------------------------
# DEVNET CONFIGURATION
# -------------------------------------------------------------------------


[node]
name = "helium-node"
rpc_bind = "0.0.0.0:20443"
#working_dir = "/tmp/stacks-blockchain-data"

[burnchain]
chain = "bitcoin"
mode = "mocknet"
commit_anchor_block_within = 10000

[[mstx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000
# secretKey = "cb3df38053d132895220b9ce471f6b676db5b9bf0b4adefb55f2118ece2478df01"

[[mstx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000
# secretKey = "21d43d2ae0da1d9d04cfcaac7d397a33733881081f0b2cd038062cf0ccbb752601"

[[mstx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000
# secretKey = "c71700b07d520a8c9731e4d0f095aa6efb91e16e25fb27ce2b72e7b698f8127a01"

[[mstx_balance]]
address = "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
amount = 10000000000000000
# secretKey = "e75dcb66f84287eaf347955e94fa04337298dbd95aa0dbb985771104ef1913db01"

[[mstx_balance]]
address = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"
amount = 10000000000000000
# secretKey = "753b7cc01a1a2e86221266a154af739463fce51219d97e4f856cd7200c3bd2a601"
# mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"

[[events_observer]]
endpoint = "host.docker.internal:3501"
retry_count = 255
events_keys = ["*"]


# -------------------------------------------------------------------------
# TESTNET CONFIGURATION
# -------------------------------------------------------------------------

# [node]
# bootstrap_node = "047435c194e9b01b3d7f7a2802d6684a3af68d05bbf4ec8f17021980d777691f1d51651f7f1d566532c804da506c117bbf79ad62eea81213ba58f8808b4d9504ad@xenon.blockstack.org:20444"
# miner = false
# working_dir = "/tmp/stacks-blockchain-data"

# [burnchain]
# mode = "xenon"
# peer_host = "bitcoind.xenon.blockstack.org"
# peer_port = 18333
# rpc_port = 18332
# magic_bytes = "T2"

# [[ustx_balance]]
# address = "ST2QKZ4FKHAH1NQKYKYAYZPY440FEPK7GZ1R5HBP2"
# amount = 10000000000000000

# [[ustx_balance]]
# address = "ST319CF5WV77KYR1H3GT0GZ7B8Q4AQPY42ETP1VPF"
# amount = 10000000000000000

# [[ustx_balance]]
# address = "ST221Z6TDTC5E0BYR2V624Q2ST6R0Q71T78WTAX6H"
# amount = 10000000000000000

# [[ustx_balance]]
# address = "ST2TFVBMRPS5SSNP98DQKQ5JNB2B6NZM91C4K3P7B"
# amount = 10000000000000000

# [[events_observer]]
# endpoint = "host.docker.internal:3501"
# retry_count = 255
# events_keys = ["*"]